[project]
name = "time-tracker"
version = "0.1.0"
description = "An app that tracks time spent using desktop applications like, browsers, vscode, etc"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "psutil>=7.2.2",
    "pydantic>=2.13.4",
    "pywin32>=311",
    "typer>=0.26.8",
    "uuid>=1.30",
]
